### ISSUE TITLE
Consulta sobre tokens

### ISSUE THREAD

**Issue by nawealvarez** [LlibertadApp/frontend#14]
Buenas, estoy laburando en la validacion del token, pero los mocks que estan no tienen la exp date. Usaron alguna herramienta para generar los mocks? Sera posible modificarlos para poder ser validados a posteriori> 
Gracias

**Comment by AlhuayOscar** [comment]
Lo consultaré

**Comment by santi28** [comment]
@nawealvarez No,la expiration todavía no la implementamos debido a que estamos trabajando con datos mock. Ni bien el backend este desplegado vamos a implementar el token con alguna librería como jwt o OAuth para atacar ese problema.
